repos:
  - repo: local
    hooks:
      - id: build
        name: build
        description: Check if all files can be compiled
        entry: v .
        language: system
        pass_filenames: false
      - id: fmt
        name: fmt
        description: Check if all files formatted
        entry: v fmt -w .
        language: system
        pass_filenames: false
      - id: test
        name: test
        description: Check if all test passed (will be migrated to CI)
        entry: v test .
        language: system

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
