repos:
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        description: Check if all files formatted
        entry: v fmt -w .
        language: system
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
