name: CI

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "**.v"
      - v.mod
env:
  MAIN: rvev.v
  MODULES: modules

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout V
        uses: actions/checkout@v3
        with:
          repository: vlang/v
          path: vlang/v
      - name: Build V
        run: cd vlang/v && make
      - name: Format
        run: vlang/v/v fmt -verify $MODULES $MAIN
      - name: Test
        run: vlang/v/v test $MODULES
